import { describe, it, expect } from 'vitest';
import { formatReleaseNotes } from '../../src/core/formatter.js';
import type { ReleaseNotesData, ReleaseJetConfig } from '../../src/types.js';

const defaultConfig: ReleaseJetConfig = {
  provider: { type: 'gitlab', url: 'https://gitlab.example.com' },
  source: 'issues',
  clients: [{ prefix: 'mobile', label: 'MOBILE' }],
  categories: {
    feature: 'New Features',
    bug: 'Bug Fixes',
    improvement: 'Improvements',
    'breaking-change': 'Breaking Changes',
  },
  uncategorized: 'lenient',
};

describe('formatReleaseNotes', () => {
  it('formats multi-client release with all sections', () => {
    const data: ReleaseNotesData = {
      tagName: 'mobile-v0.1.17',
      version: '0.1.17',
      clientPrefix: 'mobile',
      date: '2026-04-08',
      milestone: { title: '[MOBILE] Demo 1', url: 'https://gitlab.example.com/mobile/app/-/milestones/1' },
      projectUrl: 'https://gitlab.example.com/mobile/app',
      issues: {
        categorized: {
          'New Features': [
            { number:142, title: 'Dark mode support', labels: ['feature', 'MOBILE'], closedAt: '', webUrl: '', milestone: null },
            { number:137, title: 'Export as PDF', labels: ['feature', 'MOBILE'], closedAt: '', webUrl: '', milestone: null },
          ],
          'Bug Fixes': [
            { number:155, title: 'Login redirect loop', labels: ['bug', 'MOBILE'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [
          { number:151, title: 'Update dependencies', labels: ['MOBILE'], closedAt: '', webUrl: '', milestone: null },
        ],
      },
      totalCount: 4,
      uncategorizedCount: 1,
    };

    const result = formatReleaseNotes(data, defaultConfig);

    expect(result).toContain('## MOBILE v0.1.17');
    expect(result).toContain('**Released:** 2026-04-08 | **Tag:** [mobile-v0.1.17](https://gitlab.example.com/mobile/app/-/tags/mobile-v0.1.17) | **Milestone:** [[MOBILE] Demo 1](https://gitlab.example.com/mobile/app/-/milestones/1) | **Issues:** 4 closed | 1 uncategorized');
    expect(result).toContain('#### New Features');
    expect(result).toContain('- Dark mode support (#142)');
    expect(result).toContain('- Export as PDF (#137)');
    expect(result).toContain('#### Bug Fixes');
    expect(result).toContain('- Login redirect loop (#155)');
    expect(result).toContain('#### Other');
    expect(result).toContain('- Update dependencies (#151)');
    expect(result).toContain('*Generated by [ReleaseJet]');
  });

  it('formats single-client release without prefix in title', () => {
    const data: ReleaseNotesData = {
      tagName: 'v1.0.0',
      version: '1.0.0',
      clientPrefix: null,
      date: '2026-04-08',
      milestone: null,
      projectUrl: 'https://gitlab.example.com/mobile/app',
      issues: {
        categorized: {
          'Bug Fixes': [
            { number:10, title: 'Fix crash', labels: ['bug'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [],
      },
      totalCount: 1,
      uncategorizedCount: 0,
    };

    const result = formatReleaseNotes(data, defaultConfig);

    expect(result).toContain('## v1.0.0');
    expect(result).not.toContain('**Milestone:**');
    expect(result).toContain('**Issues:** 1 closed');
    expect(result).not.toContain('uncategorized');
  });

  it('omits empty category sections', () => {
    const data: ReleaseNotesData = {
      tagName: 'v1.0.0',
      version: '1.0.0',
      clientPrefix: null,
      date: '2026-04-08',
      milestone: null,
      projectUrl: 'https://gitlab.example.com/mobile/app',
      issues: {
        categorized: {
          'Bug Fixes': [
            { number:10, title: 'Fix crash', labels: ['bug'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [],
      },
      totalCount: 1,
      uncategorizedCount: 0,
    };

    const result = formatReleaseNotes(data, defaultConfig);

    expect(result).toContain('#### Bug Fixes');
    expect(result).not.toContain('### New Features');
    expect(result).not.toContain('#### Improvements');
    expect(result).not.toContain('#### Breaking Changes');
    expect(result).not.toContain('#### Other');
  });

  it('preserves category order from config', () => {
    const data: ReleaseNotesData = {
      tagName: 'v1.0.0',
      version: '1.0.0',
      clientPrefix: null,
      date: '2026-04-08',
      milestone: null,
      projectUrl: 'https://gitlab.example.com/mobile/app',
      issues: {
        categorized: {
          'Bug Fixes': [
            { number:2, title: 'Bug', labels: ['bug'], closedAt: '', webUrl: '', milestone: null },
          ],
          'New Features': [
            { number:1, title: 'Feature', labels: ['feature'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [],
      },
      totalCount: 2,
      uncategorizedCount: 0,
    };

    const result = formatReleaseNotes(data, defaultConfig);
    const featureIdx = result.indexOf('#### New Features');
    const bugIdx = result.indexOf('#### Bug Fixes');
    expect(featureIdx).toBeLessThan(bugIdx);
  });

  it('does not render "Other" section in strict mode', () => {
    const strictConfig: ReleaseJetConfig = { ...defaultConfig, uncategorized: 'strict' };
    const data: ReleaseNotesData = {
      tagName: 'v1.0.0',
      version: '1.0.0',
      clientPrefix: null,
      date: '2026-04-08',
      milestone: null,
      projectUrl: 'https://gitlab.example.com/mobile/app',
      issues: {
        categorized: {
          'New Features': [
            { number:1, title: 'Feature', labels: ['feature'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [
          { number:2, title: 'Unlabeled', labels: [], closedAt: '', webUrl: '', milestone: null },
        ],
      },
      totalCount: 2,
      uncategorizedCount: 1,
    };

    const result = formatReleaseNotes(data, strictConfig);
    expect(result).not.toContain('#### Other');
    expect(result).not.toContain('Unlabeled');
  });

  it('uses GitHub tag URL pattern when provider is github', () => {
    const githubConfig: ReleaseJetConfig = {
      provider: { type: 'github', url: 'https://github.com' },
      source: 'issues',
      clients: [],
      categories: {
        feature: 'New Features',
      },
      uncategorized: 'lenient',
    };

    const data: ReleaseNotesData = {
      tagName: 'v1.0.0',
      version: '1.0.0',
      clientPrefix: null,
      date: '2026-04-08',
      milestone: null,
      projectUrl: 'https://github.com/owner/repo',
      issues: {
        categorized: {
          'New Features': [
            { number: 10, title: 'New feature', labels: ['feature'], closedAt: '', webUrl: '', milestone: null },
          ],
        },
        uncategorized: [],
      },
      totalCount: 1,
      uncategorizedCount: 0,
    };

    const result = formatReleaseNotes(data, githubConfig);

    expect(result).toContain('**Tag:** [v1.0.0](https://github.com/owner/repo/releases/tag/v1.0.0)');
    expect(result).not.toContain('/-/tags/');
  });
});
