import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { PluginContext, FormatterFn } from '@makispps/releasejet/plugin';
import { clearTemplateCache } from '@makispps/releasejet/plugin/templates';
import plugin from '../src/index.js';
import { fullData, githubConfig } from './fixtures.js';

function createMockContext(): PluginContext & { formatters: Map<string, FormatterFn> } {
  const formatters = new Map<string, FormatterFn>();
  return {
    formatters,
    registerFormatter: vi.fn((name: string, fn: FormatterFn) => {
      formatters.set(name, fn);
    }),
    registerCommand: vi.fn(),
    extendCommand: vi.fn(),
    hooks: {
      beforeFormat: { on: vi.fn() },
      afterPublish: { on: vi.fn() },
    },
    config: githubConfig,
    logger: { debug: vi.fn() },
  };
}

beforeEach(() => {
  clearTemplateCache();
});

describe('Pro plugin integration', () => {
  it('has correct plugin metadata', () => {
    expect(plugin.name).toBe('@releasejet/pro');
    expect(plugin.version).toBe('1.0.0');
    expect(plugin.apiVersion).toBe(1);
    expect(typeof plugin.register).toBe('function');
  });

  it('registers all three preset formatters', () => {
    const ctx = createMockContext();
    plugin.register(ctx);

    expect(ctx.registerFormatter).toHaveBeenCalledTimes(3);
    expect(ctx.formatters.has('compact')).toBe(true);
    expect(ctx.formatters.has('detailed')).toBe(true);
    expect(ctx.formatters.has('changelog')).toBe(true);
  });

  it('compact formatter produces valid markdown', () => {
    const ctx = createMockContext();
    plugin.register(ctx);

    const formatter = ctx.formatters.get('compact')!;
    const result = formatter(fullData, githubConfig);

    expect(result).toContain('## v1.2.0 (2026-04-14)');
    expect(result).toContain('**Bug Fixes**');
    expect(result).toContain('- Fix login timeout (#42)');
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });

  it('detailed formatter produces valid markdown with linked issues', () => {
    const ctx = createMockContext();
    plugin.register(ctx);

    const formatter = ctx.formatters.get('detailed')!;
    const result = formatter(fullData, githubConfig);

    expect(result).toContain('# v1.2.0');
    expect(result).toContain('[#42](https://github.com/owner/repo/issues/42)');
    expect(result).toContain('#### Contributors');
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });

  it('changelog formatter produces valid markdown', () => {
    const ctx = createMockContext();
    plugin.register(ctx);

    const formatter = ctx.formatters.get('changelog')!;
    const result = formatter(fullData, githubConfig);

    expect(result).toContain('## [1.2.0] - 2026-04-14');
    expect(result).toContain('### Bug Fixes');
    expect(result).toContain('- Fix login timeout (#42)');
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });
});
