import type { ReleaseNotesData, ReleaseJetConfig } from '../types.js';

export function formatReleaseNotes(
  data: ReleaseNotesData,
  config: ReleaseJetConfig,
): string {
  const lines: string[] = [];

  // Title
  const title = data.clientPrefix
    ? `${data.clientPrefix.toUpperCase()} v${data.version}`
    : `v${data.version}`;
  lines.push(`## ${title}`);
  lines.push('');

  // Metadata (single line, pipe-separated)
  const tagUrl = config.provider.type === 'github'
    ? `${data.projectUrl}/releases/tag/${data.tagName}`
    : `${data.projectUrl}/-/tags/${data.tagName}`;

  const metaParts = [
    `**Released:** ${data.date}`,
    `**Tag:** [${data.tagName}](${tagUrl})`,
  ];
  if (data.milestone) {
    metaParts.push(`**Milestone:** [${data.milestone.title}](${data.milestone.url})`);
  }
  const issuesSummary =
    data.uncategorizedCount > 0
      ? `${data.totalCount} closed | ${data.uncategorizedCount} uncategorized`
      : `${data.totalCount} closed`;
  metaParts.push(`**Issues:** ${issuesSummary}`);
  lines.push(metaParts.join(' | '));
  lines.push('');
  lines.push('---');
  lines.push('');

  // Category sections in config order
  const categoryOrder = Object.values(config.categories);
  for (const heading of categoryOrder) {
    const issues = data.issues.categorized[heading];
    if (!issues || issues.length === 0) continue;
    lines.push(`#### ${heading}`);
    for (const issue of issues) {
      lines.push(`- ${issue.title} (#${issue.number})`);
    }
    lines.push('');
  }

  // Uncategorized (lenient mode only)
  if (
    data.issues.uncategorized.length > 0 &&
    config.uncategorized === 'lenient'
  ) {
    lines.push('#### Other');
    for (const issue of data.issues.uncategorized) {
      lines.push(`- ${issue.title} (#${issue.number})`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [ReleaseJet](https://github.com/makisp/releasejet)*');

  return lines.join('\n');
}
