import { describe, it, expect } from 'vitest';
import Handlebars from 'handlebars';
import { buildTemplateContext } from '@makispps/releasejet/plugin/templates';
import changelogSource from '../../src/templates/changelog.hbs';
import { fullData, minimalData, multiClientData, uncategorizedData, githubConfig } from '../fixtures.js';

function render(data: Parameters<typeof buildTemplateContext>[0], config: Parameters<typeof buildTemplateContext>[1]) {
  const template = Handlebars.compile(changelogSource, { noEscape: true });
  const ctx = buildTemplateContext(data, config);
  return template(ctx);
}

describe('changelog template', () => {
  it('renders Keep a Changelog header format', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('## [1.2.0] - 2026-04-14');
  });

  it('uses ### for category headings', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('### Bug Fixes');
    expect(result).toContain('### New Features');
  });

  it('renders plain issue numbers (not linked)', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('- Fix login timeout (#42)');
    expect(result).toContain('- Handle null avatar (#38)');
    expect(result).toContain('- Add dark mode (#45)');
    // Should NOT be linked
    expect(result).not.toContain('[#42]');
  });

  it('does not include metadata line', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('**Released:**');
    expect(result).not.toContain('**Tag:**');
  });

  it('does not include contributors', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('Contributors');
  });

  it('does not include horizontal rules', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('---');
  });

  it('includes ReleaseJet footer', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });

  it('renders multi-client prefix in heading', () => {
    const result = render(multiClientData, githubConfig);
    expect(result).toContain('## [MOBILE v1.2.0] - 2026-04-14');
  });

  it('renders uncategorized issues in lenient mode', () => {
    const result = render(uncategorizedData, githubConfig);
    expect(result).toContain('### Other');
    expect(result).toContain('- Unlabeled task (#99)');
  });
});
