import { describe, it, expect } from 'vitest';
import Handlebars from 'handlebars';
import { buildTemplateContext } from '@makispps/releasejet/plugin/templates';
import compactSource from '../../src/templates/compact.hbs';
import { fullData, minimalData, multiClientData, uncategorizedData, githubConfig } from '../fixtures.js';

function render(data: Parameters<typeof buildTemplateContext>[0], config: Parameters<typeof buildTemplateContext>[1]) {
  const template = Handlebars.compile(compactSource, { noEscape: true });
  const ctx = buildTemplateContext(data, config);
  return template(ctx);
}

describe('compact template', () => {
  it('renders version and date heading', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('## v1.2.0 (2026-04-14)');
  });

  it('renders categories as bold headings with plain issue numbers', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('**Bug Fixes**');
    expect(result).toContain('- Fix login timeout (#42)');
    expect(result).toContain('- Handle null avatar (#38)');
    expect(result).toContain('**New Features**');
    expect(result).toContain('- Add dark mode (#45)');
  });

  it('does not include metadata line', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('**Released:**');
    expect(result).not.toContain('**Tag:**');
    expect(result).not.toContain('**Milestone:**');
  });

  it('does not include contributors', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('Contributors');
    expect(result).not.toContain('@alice');
  });

  it('does not include horizontal rules', () => {
    const result = render(fullData, githubConfig);
    expect(result).not.toContain('---');
  });

  it('includes ReleaseJet footer', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });

  it('renders multi-client prefix in heading', () => {
    const result = render(multiClientData, githubConfig);
    expect(result).toContain('## MOBILE v1.2.0 (2026-04-14)');
  });

  it('renders uncategorized issues in lenient mode', () => {
    const result = render(uncategorizedData, githubConfig);
    expect(result).toContain('**Other**');
    expect(result).toContain('- Unlabeled task (#99)');
  });

  it('omits empty categories', () => {
    const result = render(minimalData, githubConfig);
    expect(result).toContain('**Bug Fixes**');
    expect(result).not.toContain('**New Features**');
    expect(result).not.toContain('**Improvements**');
  });
});
