import { describe, it, expect } from 'vitest';
import Handlebars from 'handlebars';
import { buildTemplateContext } from '@makispps/releasejet/plugin/templates';
import detailedSource from '../../src/templates/detailed.hbs';
import { fullData, minimalData, multiClientData, uncategorizedData, githubConfig } from '../fixtures.js';

function render(data: Parameters<typeof buildTemplateContext>[0], config: Parameters<typeof buildTemplateContext>[1]) {
  const template = Handlebars.compile(detailedSource, { noEscape: true });
  const ctx = buildTemplateContext(data, config);
  return template(ctx);
}

describe('detailed template', () => {
  it('renders h1 heading with version', () => {
    const result = render(fullData, githubConfig);
    expect(result).toMatch(/^# v1\.2\.0\n/);
  });

  it('renders full metadata line', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('**Released:** 2026-04-14');
    expect(result).toContain('**Tag:** [v1.2.0]');
    expect(result).toContain('**Milestone:** [Sprint 12]');
    expect(result).toContain('**Issues:** 3 closed');
  });

  it('renders linked issue numbers', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('[#42](https://github.com/owner/repo/issues/42)');
    expect(result).toContain('[#38](https://github.com/owner/repo/issues/38)');
    expect(result).toContain('[#45](https://github.com/owner/repo/issues/45)');
  });

  it('renders category sections with #### headings', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('#### Bug Fixes');
    expect(result).toContain('#### New Features');
  });

  it('includes horizontal rules', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('---');
  });

  it('renders contributors section', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('#### Contributors');
    expect(result).toContain('[@alice](https://github.com/alice)');
    expect(result).toContain('[@bob](https://github.com/bob)');
  });

  it('omits contributors section when none present', () => {
    const result = render(minimalData, githubConfig);
    expect(result).not.toContain('#### Contributors');
  });

  it('omits milestone from metadata when not present', () => {
    const result = render(minimalData, githubConfig);
    expect(result).not.toContain('**Milestone:**');
  });

  it('includes ReleaseJet footer', () => {
    const result = render(fullData, githubConfig);
    expect(result).toContain('*Generated by [ReleaseJet](https://www.releasejet.dev)*');
  });

  it('renders multi-client prefix in heading', () => {
    const result = render(multiClientData, githubConfig);
    expect(result).toMatch(/^# MOBILE v1\.2\.0\n/);
  });

  it('renders uncategorized issues in lenient mode with links', () => {
    const result = render(uncategorizedData, githubConfig);
    expect(result).toContain('#### Other');
    expect(result).toContain('[#99](https://github.com/owner/repo/issues/99)');
  });
});
