// Default release-notes template. Authored in Handlebars syntax.
// Kept as a TypeScript string (not a .hbs file) so the docs emitter
// can run under tsx without a custom loader.
export const defaultTemplate = `## {{title}}

{{metaLine}}

---

{{#each categoryEntries}}
#### {{this.heading}}
{{#each this.issues}}
- {{this.title}} (#{{this.number}})
{{/each}}

{{/each}}
{{#if showUncategorized}}
#### Other
{{#each uncategorizedEntries}}
- {{this.title}} (#{{this.number}})
{{/each}}

{{/if}}
{{#if hasContributors}}
#### Contributors
{{contributorsList}}

{{/if}}
---

*Generated by [ReleaseJet](https://github.com/makisp/releasejet)*`;
